# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-02-02 00:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dakoku',
            fields=[
                ('dakokuID', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True, verbose_name='\u6253\u523b\u65e5\u6642')),
                ('Bikou', models.TextField(blank=True, null=True, verbose_name='\u5099\u8003')),
                ('sakujoFlag', models.BooleanField(default=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
            ],
        ),
        migrations.CreateModel(
            name='DakokuKubun',
            fields=[
                ('KubunID', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('statusMei', models.CharField(max_length=255, verbose_name='\u533a\u5206\u540d')),
                ('KoushinJikan', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u6642\u9593')),
                ('KoushinUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u66f4\u65b0\u30e6\u30fc\u30b6\u30fc')),
            ],
        ),
        migrations.CreateModel(
            name='DakokuMethod',
            fields=[
                ('dakokuMethodID', models.AutoField(primary_key=True, serialize=False, verbose_name='\u6253\u523b\u65b9\u6cd5ID')),
                ('dakouMethodMei', models.CharField(max_length=50, verbose_name='\u6253\u523b\u65b9\u6cd5\u540d')),
                ('sakujoFlag', models.BooleanField(default=False, verbose_name='\u524a\u9664\u30d5\u30e9\u30b0')),
                ('KoushinJikan', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u6642\u9593')),
                ('KoushinUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u66f4\u65b0\u30e6\u30fc\u30b6\u30fc')),
            ],
        ),
        migrations.CreateModel(
            name='IDmUser',
            fields=[
                ('IDm', models.CharField(help_text='IDm\u306f\u3001FeliCa\u30ab\u30fc\u30c9\u88fd\u9020\u6642\u306b\uff29\uff23\u30c1\u30c3\u30d7\u306b\u8a18\u9332\u3055\u308c\u66f8\u304d\u63db\u3048\u304c\u3067\u304d\u306a\u3044\u56fa\u6709\u306e\uff29\uff24\u756a\u53f7\u3067\u3042\u308b\u3002IDm\u306f8byte\uff0816\u6841\uff09\u306e\u6570\u5b57', max_length=16, primary_key=True, serialize=False, verbose_name='IDm')),
                ('bikou', models.TextField(blank=True, default='', help_text='IDm \xd7 UserID \u306b\u95a2\u3059\u308b\u5099\u8003', max_length=2000, verbose_name='\u5099\u8003')),
                ('user', models.OneToOneField(help_text='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u30e6\u30fc\u30b6\u30fcID')),
            ],
        ),
        migrations.CreateModel(
            name='KinmuKubun',
            fields=[
                ('KinmuKubunID', models.AutoField(primary_key=True, serialize=False, verbose_name='\u52e4\u52d9\u533a\u5206ID')),
                ('KinmuKubunMei', models.CharField(max_length=50, verbose_name='\u533a\u5206\u540d')),
                ('KoushinJikan', models.DateTimeField(auto_now_add=True, null=True)),
                ('KoushinUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u66f4\u65b0\u30e6\u30fc\u30b6\u30fc')),
            ],
        ),
        migrations.AddField(
            model_name='dakoku',
            name='dakokuMethodID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kintai.DakokuMethod', verbose_name='\u6253\u523b\u65b9\u6cd5'),
        ),
        migrations.AddField(
            model_name='dakoku',
            name='dakokuStatusID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kintai.DakokuKubun', verbose_name='\u6253\u523b\u533a\u5206'),
        ),
        migrations.AddField(
            model_name='dakoku',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u30e6\u30fc\u30b6\u30fc'),
        ),
    ]
